{% set name = "pkgversions" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pkgversions-{{ version }}.tar.gz
  sha256: 0ff0f688a4f75d78c303c34a9712dd8eae3f3fdaac3add68d81899471f5b45c1

build:
  number: 1
  noarch: python
  entry_points:
    - pkgversions=pkgversions.PkgVersions:commandHandler
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - python >={{ python_min }}

test:
  imports:
    - pkgversions
    - pkgversions.resources
  commands:
    - pip check
    - pkgversions --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hasii2011/pkgversions
  summary: A build help tool for updating package versions during development.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
